Korean translation
humphd/have-fun-with-machine-learning pull request #29
Opened 2021-12-08 13:25 UTC by zaysverse

issue #28

2021-12-08 14:11 UTC, humphd commented
cc @suhhee1011, in case you want to review (no pressure).

2021-12-09 19:05 UTC, suhhee1011 commented on README_ko-KR.md
> +이 가이드에서 우리의 목표는 기계학습을 이용하여 [데이터/훈련되지않은 샘플들](data/untrained-samples)
기계학습보다는 머신러닝이라고 쓰는건 어떨까요? 한국에서 기계학습이라고 번역하는것보다는 머신러닝이라고 부르는경우가 더 많은 것 같아요 ㅎㅎ

2021-12-09 19:05 UTC, suhhee1011 commented on README_ko-KR.md
> +* 이미지 데이터셋를 만듭니다.
를->을

2021-12-09 19:05 UTC, suhhee1011 commented on README_ko-KR.md
> +* 기존 신경망을 하게 튜닝 -*fine Tuning*- 해 신경망의 정확성을 향상시킵니다. (AlexNet 와 GoogLeNet)
"하게" 앞에 뭔가 빠진것 같네요 ㅎㅎ

2021-12-09 19:05 UTC, suhhee1011 commented on README_ko-KR.md
> +* C++, 파이썬을 지원합니다.([node.js 지원](https://github.com/silklabs/node-caffe) 예정)
C++,python ->C++과 python

2021-12-09 19:05 UTC, suhhee1011 commented on README_ko-KR.md
> + 데 필요한 모든 것이 `build/` 디렉터로에 있을 것입니다. `build/`의 상위 디렉토리는 `CAFFE_ROOT`(나중에 필요)입니다.
디렉터로 ->디렉터리

2021-12-09 19:05 UTC, suhhee1011 commented on README_ko-KR.md
> +여기 각 디렉토리는 분류할 카테고리이며, 해당 카테고리 디렉토리 내의 각 이미지는 훈련 및 검증에
여기 각 디렉토리는 분류할 카테고리이며, ->여기 각 디렉토리는 이미지를 분류할 카테고리이며,

2021-12-11 13:47 UTC, zaysverse commented on README_ko-KR.md
> +여기 각 디렉토리는 분류할 카테고리이며, 해당 카테고리 디렉토리 내의 각 이미지는 훈련 및 검증에
감사합니다 눈에 안보인 오타가 생각보다 많았네요 ㅎㅎ!

2021-12-11 15:08 UTC, humphd commented
@suhhee1011 want to take another look when you have a min?

2021-12-15 20:07 UTC, humphd requested changes
Can you please add a link to the main README to indicate it's available in Korean as well, like this:

https://github.com/humphd/have-fun-with-machine-learning/blob/master/README.md?plain=1#L2

Next, can you please add your name and whatever link you want for yourself on line 4, like this:

https://github.com/humphd/have-fun-with-machine-learning/blob/master/README_zh-tw.md?plain=1#L4

I can't comment on the translation itself, and I'll assume you've dealt with @suhhee1011's comments?  If not, please do that and I'll merge once you address the above.

Nice work.

2021-12-15 21:47 UTC, suhhee1011 commented on README_ko-KR.md
> +우리는 훈련 시도에 돌고래와 해마의 작은 데이터셋를 사용할 것입니다. [data/dolphins-and-seahorses](data/dolphins-and-seahorses)에 제가 사용했던 이미지들을 넣어두었습니다. 2개 이상의 카테고리가 필요하고 여러분은 더
를->을

2021-12-15 21:49 UTC, suhhee1011 requested changes

2021-12-15 21:49 UTC, suhhee1011 commented on README_ko-KR.md
> +우리는 훈련 시도에 돌고래와 해마의 작은 데이터셋를 사용할 것입니다. [data/dolphins-and-seahorses](data/dolphins-and-seahorses)에 제가 사용했던 이미지들을 넣어두었습니다. 2개 이상의 카테고리가 필요하고 여러분은 더
혹시 이거 다른 부분도 똑같이 에러가 있던데 다 바꾸셔야 할 것 같아요 ㅎㅎ

2021-12-15 21:49 UTC, suhhee1011 commented on README_ko-KR.md
> + 데 필요한 모든 것이 `build/` 디렉터로에 있을 것입니다. `build/`의 상위 디렉터리는 `CAFFE_ROOT`(나중에 필요)입니다.
디렉터로->디렉터리 아직 안바뀌어 있네요 ㅠㅠ

2021-12-19 00:03 UTC, humphd commented
@suhhee1011 good to merge?

2021-12-19 00:04 UTC, humphd commented
@zaysverse looks like this got missed:

> Can you please add a link to the main README to indicate it's available in Korean as well, like this:

https://github.com/humphd/have-fun-with-machine-learning/blob/master/README.md?plain=1#L2

Can you include that too?

2021-12-19 00:47 UTC, zaysverse commented on README_ko-KR.md
> + 데 필요한 모든 것이 `build/` 디렉터로에 있을 것입니다. `build/`의 상위 디렉터리는 `CAFFE_ROOT`(나중에 필요)입니다.
봐주셔서 정말 감사합니다. 언급하신 부분들 다시 찾아보고 수정했습니다!

2021-12-19 00:53 UTC, zaysverse commented
I've done. I translated it while studying and it was fun. Thank you for this detailed tutorial :)

2021-12-19 00:58 UTC, zaysverse commented
I'm sorry. I was a bit late because I was reviewing the whole thing finally.

2021-12-19 18:38 UTC, humphd commented
Absent a response from @suhhee1011, I'm going to merge this.  If there are issues, people can fix in follow-ups.  Thanks a lot for all the work @zaysverse, I hope other Korean speakers benefit from your efforts!

2021-12-19 18:38 UTC, merged

2021-12-20 02:32 UTC, BirkhoffLee commented
Hooray!

> On 20 Dec 2021, at 02:39, David Humphrey ***@***.***> wrote:
> 
> ﻿
> Merged #29 into master.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.